# Generated by Django 2.1.7 on 2019-03-05 21:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1500)),
                ('adv_type', models.CharField(choices=[('hotel', 'hotel'), ('private', 'private')], max_length=255)),
                ('accepted_animals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('horse', 'horse'), ('bird', 'bird'), ('reptile', 'reptile')], max_length=255), size=None)),
                ('pros', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'blisko miasta'), ('2', 'z dala od miasta'), ('3', 'w centrum miasta')], max_length=255), size=None)),
                ('price_per_day', models.IntegerField(default=0)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to='advertisements'), size=None)),
                ('phone', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
            ],
        ),
    ]
