# Generated by Django 2.1.7 on 2019-03-06 16:51

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements')),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='images',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='pros',
            field=website.models.ChoiceArrayField(base_field=models.CharField(choices=[('1', 'blisko miasta'), ('2', 'z dala od miasta'), ('3', 'w centrum miasta')], max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='advertisementimg',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Advertisement'),
        ),
    ]
