# Generated by Django 2.1.7 on 2019-03-06 17:00

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190306_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='accepted_animals',
            field=website.models.ChoiceArrayField(base_field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('horse', 'horse'), ('bird', 'bird'), ('reptile', 'reptile')], max_length=255), default=list, size=None),
        ),
    ]
